<a href="https://colab.research.google.com/github/LYZAcell/data_study/blob/main/%EC%9D%B8%EA%B5%AC%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%A0%84%EC%B2%98%EB%A6%AC2_0819.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import files

# 1. df transpose전 (실행 쭉쭉)

In [2]:
df = pd.read_csv('./행정구역_연도별_총주민등록인구.csv', encoding='euc-kr')
df.head()

,행정구역(시군구)별,연령별,항목,단위,2024.07 월,2008 년,2009 년,2010 년,2011 년,2012 년,...,2015 년,2016 년,2017 년,2018 년,2019 년,2020 년,2021 년,2022 년,2023 년,Unnamed: 21
0,전국,계,총인구수[명],명,51265238,49540367.0,49773145.0,50515666.0,50734284.0,50948272,...,51529338,51696216,51778544,51826059,51849861,51829023,51638809,51439038,51325329,NaN
1,전국,계,남자인구수[명],명,25528507,24822897.0,24929939.0,25310385.0,25406934.0,25504060,...,25758186,25827594,25855919,25866129,25864816,25841029,25746684,25636951,25565736,NaN
2,전국,계,여자인구수[명],명,25736731,24717470.0,24843206.0,25205281.0,25327350.0,25444212,...,25771152,25868622,25922625,25959930,25985045,25987994,25892125,25802087,25759593,NaN
3,전국,0세,총인구수[명],명,223834,444421.0,424529.0,448516.0,451579.0,464374,...,424563,393674,345786,317685,295132,265087,253946,244250,225958,NaN
4,전국,0세,남자인구수[명],명,114623,228977.0,218756.0,231521.0,231954.0,238639,...,217775,201541,178138,162950,151494,135661,130157,124860,115707,NaN

In [3]:
# 열 이름 필터링
cols_age = ['연령별', '6세','7세','8세','9세','10세','11세','12세','13세','14세','15세','16세','17세']

# 필터링 후 인덱스 리스트로 만들기
drop_index = df[~df['연령별'].isin(cols_age)].index

# 해당 인덱스 드롭하기
df_filtered = df.drop(drop_index)

df_filtered

,행정구역(시군구)별,연령별,항목,단위,2024.07 월,2008 년,2009 년,2010 년,2011 년,2012 년,...,2015 년,2016 년,2017 년,2018 년,2019 년,2020 년,2021 년,2022 년,2023 년,Unnamed: 21
21,전국,6세,총인구수[명],명,346359,494660.0,493040.0,473718.0,435724.0,449057,...,447817,473401,476061,489604,441362,440710,444555,413162,364740,NaN
22,전국,6세,남자인구수[명],명,177625,258531.0,256152.0,245698.0,225690.0,232273,...,230602,244059,244330,251225,226090,225736,227809,211336,187700,NaN
23,전국,6세,여자인구수[명],명,168734,236129.0,236888.0,228020.0,210034.0,216784,...,217215,229342,231731,238379,215272,214974,216746,201826,177040,NaN
24,전국,7세,총인구수[명],명,382519,559549.0,494611.0,493551.0,473970.0,435863,...,468546,448049,473580,476168,489772,441560,440866,444843,413535,NaN
25,전국,7세,남자인구수[명],명,196341,291499.0,258472.0,256412.0,245816.0,225763,...,241138,230694,244138,244333,251311,226161,225794,227921,211524,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5254,제주특별자치도,16세,남자인구수[명],명,3706,4593.0,4460.0,4648.0,4569.0,4549,...,4303,4545,4105,3769,3735,3597,3439,3536,3786,NaN
5255,제주특별자치도,16세,여자인구수[명],명,3474,3900.0,4139.0,4143.0,4195.0,4104,...,3928,4303,3712,3233,3419,3197,3036,3236,3584,NaN
5256,제주특별자치도,17세,총인구수[명],명,7091,8051.0,8457.0,8588.0,8784.0,8768,...,8273,8273,8908,7822,6987,7165,6779,6464,6760,NaN
5257,제주특별자치도,17세,남자인구수[명],명,3653,4110.0,4573.0,4462.0,4642.0,4571,...,4363,4327,4580,4112,3752,3733,3585,3434,3531,NaN
5258,제주특별자치도,17세,여자인구수[명],명,3438,3941.0,3884.0,4126.0,4142.0,4197,...,3910,3946,4328,3710,3235,3432,3194,3030,3229,NaN

In [4]:
age_filter = df_filtered.copy()
# '총인구수[명]' 항목만 선택
age_filter = age_filter[age_filter['항목'] == '총인구수[명]']

# 'Unnamed: 21' 열 제거
age_filter = age_filter.drop(columns=['Unnamed: 21'])
# 불필요한 컬럼제거
age_filter = age_filter.drop(columns=['단위','항목'])
age_filter.head(20)

,행정구역(시군구)별,연령별,2024.07 월,2008 년,2009 년,2010 년,2011 년,2012 년,2013 년,2014 년,2015 년,2016 년,2017 년,2018 년,2019 년,2020 년,2021 년,2022 년,2023 년
21,전국,6세,346359,494660.0,493040.0,473718.0,435724.0,449057,495221,468321,447817,473401,476061,489604,441362,440710,444555,413162,364740
24,전국,7세,382519,559549.0,494611.0,493551.0,473970.0,435863,449321,495536,468546,448049,473580,476168,489772,441560,440866,444843,413535
27,전국,8세,429673,639584.0,559360.0,495212.0,493658.0,474009,436031,449510,495761,468712,448183,473690,476358,489936,441672,441044,445099
30,전국,9세,447106,620098.0,639421.0,560067.0,495288.0,493679,474106,436172,449663,495918,468858,448251,473817,476474,490049,441805,441225
33,전국,10세,440406,640447.0,619828.0,640166.0,560042.0,495216,493745,474187,436313,449851,496041,468897,448401,473919,476536,490147,441952
36,전국,11세,464953,672419.0,640111.0,620740.0,640027.0,559908,495256,493804,474284,436439,449954,496074,469014,448450,473997,476573,490229
39,전국,12세,480200,686232.0,672065.0,641207.0,620650.0,639852,559931,495268,493916,474372,436496,449936,496146,469087,448481,473924,476570
42,전국,13세,489129,708751.0,685780.0,673228.0,640950.0,620407,639858,559938,495316,493970,474366,436420,449979,496175,469101,448369,473894
45,전국,14세,453461,714275.0,708234.0,687104.0,672862.0,640593,620395,639828,559996,495347,493910,474221,436418,449958,496081,468939,448324
48,전국,15세,456053,710578.0,713804.0,709686.0,686666.0,672396,640464,620320,639869,560014,495262,493626,474123,436320,449838,495811,468773
51,전국,16세,491136,724687.0,709953.0,715362.0,709218.0,686179,672216,640283,620297,639783,559804,494894,493389,473931,436095,449473,495547
54,전국,17세,467683,701323.0,723999.0,711438.0,714748.0,708614,685900,671839,640126,620107,639416,559205,494523,493036,473465,435582,449025
327,서울특별시,6세,51970,88920.0,88847.0,85570.0,76678.0,78710,84583,79615,74176,77045,75386,76957,69031,68085,67581,62376,55100
330,서울특별시,7세,57136,97818.0,88001.0,87437.0,84286.0,75315,77366,83620,78271,72626,75929,73813,76160,68257,66923,66960,62036
333,서울특별시,8세,64604,112468.0,97286.0,87174.0,86520.0,83258,74650,76662,82452,76968,71772,74748,73259,75438,67174,66454,66691
336,서울특별시,9세,67209,108022.0,112236.0,96707.0,86398.0,85720,82595,74048,75752,81236,76157,70652,74305,72676,74480,66820,66430
339,서울특별시,10세,66167,112333.0,107794.0,111856.0,96006.0,85656,85082,82076,73327,75032,80577,75180,70378,73776,71911,74250,66672
342,서울특별시,11세,70356,118696.0,112499.0,107677.0,111428.0,95388,85239,84629,81332,72584,74502,79733,74930,70062,72979,71693,74287
345,서울특별시,12세,72593,122963.0,119523.0,113036.0,107708.0,111130,95197,85274,84334,80747,72380,74074,79942,74955,69798,73139,71911
348,서울특별시,13세,74049,128461.0,122857.0,119350.0,112316.0,106908,110486,94743,84511,83494,80264,71698,73725,79461,74226,69481,72773

In [5]:
# '행정구역(시군구)별'을 인덱스로 설정합니다.
age_filter_seoul = age_filter.set_index('행정구역(시군구)별')

# 이제 '서울특별시' 행을 가져올 수 있습니다.
age_filter_seoul.loc['서울특별시']

,연령별,2024.07 월,2008 년,2009 년,2010 년,2011 년,2012 년,2013 년,2014 년,2015 년,2016 년,2017 년,2018 년,2019 년,2020 년,2021 년,2022 년,2023 년
행정구역(시군구)별,,,,,,,,,,,,,,,,,,
서울특별시,6세,51970,88920.0,88847.0,85570.0,76678.0,78710,84583,79615,74176,77045,75386,76957,69031,68085,67581,62376,55100
서울특별시,7세,57136,97818.0,88001.0,87437.0,84286.0,75315,77366,83620,78271,72626,75929,73813,76160,68257,66923,66960,62036
서울특별시,8세,64604,112468.0,97286.0,87174.0,86520.0,83258,74650,76662,82452,76968,71772,74748,73259,75438,67174,66454,66691
서울특별시,9세,67209,108022.0,112236.0,96707.0,86398.0,85720,82595,74048,75752,81236,76157,70652,74305,72676,74480,66820,66430
서울특별시,10세,66167,112333.0,107794.0,111856.0,96006.0,85656,85082,82076,73327,75032,80577,75180,70378,73776,71911,74250,66672
서울특별시,11세,70356,118696.0,112499.0,107677.0,111428.0,95388,85239,84629,81332,72584,74502,79733,74930,70062,72979,71693,74287
서울특별시,12세,72593,122963.0,119523.0,113036.0,107708.0,111130,95197,85274,84334,80747,72380,74074,79942,74955,69798,73139,71911
서울특별시,13세,74049,128461.0,122857.0,119350.0,112316.0,106908,110486,94743,84511,83494,80264,71698,73725,79461,74226,69481,72773
서울특별시,14세,70046,132339.0,128767.0,123140.0,119063.0,111864,106669,110145,94302,83929,83081,79681,71582,73398,78965,73939,69371
서울특별시,15세,70736,133649.0,133249.0,129667.0,123169.0,118800,111753,106792,110050,93942,83791,82773,79677,71470,73101,78832,73898
서울특별시,16세,77241,138416.0,133501.0,133310.0,129002.0,122232,118196,111418,106085,109021,93326,83012,82287,79105,70668,72618,78204
서울특별시,17세,74653,136284.0,138472.0,133731.0,132938.0,128406,121842,117950,110951,105498,108584,92791,82767,81820,78485,70496,72331

In [6]:
# '행정구역(시군구)별' 열의 첫 번째 행의 값을 '전체국민'으로 변경
#age_filter.at[0, '행정구역(시군구)별'] = '전체국민'
#age_filter.loc['서울특별시']

In [7]:
age_filter

,행정구역(시군구)별,연령별,2024.07 월,2008 년,2009 년,2010 년,2011 년,2012 년,2013 년,2014 년,2015 년,2016 년,2017 년,2018 년,2019 년,2020 년,2021 년,2022 년,2023 년
21,전국,6세,346359,494660.0,493040.0,473718.0,435724.0,449057,495221,468321,447817,473401,476061,489604,441362,440710,444555,413162,364740
24,전국,7세,382519,559549.0,494611.0,493551.0,473970.0,435863,449321,495536,468546,448049,473580,476168,489772,441560,440866,444843,413535
27,전국,8세,429673,639584.0,559360.0,495212.0,493658.0,474009,436031,449510,495761,468712,448183,473690,476358,489936,441672,441044,445099
30,전국,9세,447106,620098.0,639421.0,560067.0,495288.0,493679,474106,436172,449663,495918,468858,448251,473817,476474,490049,441805,441225
33,전국,10세,440406,640447.0,619828.0,640166.0,560042.0,495216,493745,474187,436313,449851,496041,468897,448401,473919,476536,490147,441952
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5244,제주특별자치도,13세,7575,8896.0,8677.0,8604.0,8184.0,8146,8740,7718,6939,7088,6796,6513,6810,7412,7032,6928,7325
5247,제주특별자치도,14세,6969,8851.0,8835.0,8663.0,8634.0,8183,8193,8785,7757,6993,7154,6815,6478,6822,7447,7018,6914
5250,제주특별자치도,15세,6955,8552.0,8739.0,8734.0,8639.0,8587,8156,8171,8797,7768,6988,7162,6788,6509,6834,7418,6984
5253,제주특별자치도,16세,7180,8493.0,8599.0,8791.0,8764.0,8653,8607,8201,8231,8848,7817,7002,7154,6794,6475,6772,7370
5256,제주특별자치도,17세,7091,8051.0,8457.0,8588.0,8784.0,8768,8674,8642,8273,8273,8908,7822,6987,7165,6779,6464,6760

In [8]:
age_filter = age_filter.groupby('행정구역(시군구)별').sum()
age_filter = age_filter.drop(columns=['연령별'])
age_filter

,2024.07 월,2008 년,2009 년,2010 년,2011 년,2012 년,2013 년,2014 년,2015 년,2016 년,2017 년,2018 년,2019 년,2020 년,2021 년,2022 년,2023 년
행정구역(시군구)별,,,,,,,,,,,,,,,,,
강원특별자치도,144209,231065.0,225409.0,218742.0,211496.0,203750,197289,189716,182164,175986,169850,163512,158292,154953,152567,149922,146225
경기도,1544274,1942889.0,1909584.0,1875660.0,1821995.0,1773344,1737086,1696658,1654342,1628738,1607290,1588365,1572292,1575249,1578287,1569408,1557472
경상남도,364138,530537.0,516568.0,500941.0,482613.0,464182,450650,436152,421520,410837,402640,393373,385946,383247,380786,375634,369245
경상북도,249044,390102.0,376805.0,362451.0,348805.0,334403,322583,310248,297976,289410,281277,272783,266874,263717,261927,258260,252275
광주광역시,166571,267449.0,262840.0,255619.0,246632.0,237455,229172,220779,211064,203076,195934,188540,182693,179217,175490,172486,169143
대구광역시,246488,413520.0,400190.0,384389.0,367327.0,349858,334730,319583,304204,293254,283141,272310,263243,258394,253438,250655,248781
대전광역시,154742,257438.0,250396.0,242895.0,235026.0,226564,219845,211463,200364,192653,185194,177566,171479,167548,163758,160384,157316
부산광역시,308901,510171.0,488489.0,464020.0,438842.0,415731,397544,379620,363614,350942,339422,329416,321577,318814,316351,314084,311374
서울특별시,816760,1430369.0,1383032.0,1328655.0,1265512.0,1203387,1153658,1106972,1055543,1012122,975749,935112,908043,888503,866291,847058,829704
세종특별자치시,65065,0.0,0.0,0.0,0.0,14853,16112,21705,31352,36787,43270,49248,53676,57006,60306,63237,64630
울산광역시,128905,201868.0,194048.0,185889.0,177696.0,169975,163459,157358,151163,146442,142045,138118,135225,134384,133098,132100,130447
인천광역시,317310,448432.0,433572.0,417376.0,401980.0,388190,377931,366826,355648,347667,339919,331617,325166,321283,319584,319348,318966
전국,5348678,7872603.0,7660206.0,7421479.0,7143803.0,6875773,6662444,6445006,6221904,6055963,5911931,5760986,5643302,5589556,5540736,5479672,5408913
전라남도,178488,294267.0,285126.0,274115.0,262916.0,251525,241760,232156,222914,215734,208827,201351,195127,191170,188443,185073,181396
전북특별자치도,181191,298909.0,291159.0,282128.0,271967.0,260920,251906,242451,233051,225160,217936,209514,202377,197878,194021,189392,184643
제주특별자치도,82953,99134.0,97435.0,95168.0,92616.0,90333,88993,87507,86312,85886,85794,85057,84108,84639,85063,84943,84005
충청남도,234008,310291.0,305152.0,299842.0,292935.0,274400,269565,263346,256498,252448,249956,245999,241935,240101,239359,237879,235934
충청북도,165631,246162.0,240401.0,233589.0,225445.0,216903,210161,202466,194175,188821,183687,179105,175249,173453,171967,169809,167357

# 3.지역별 groupby완료
- 아동1, 2 분리
-  컬럼맞추기

In [9]:
#복사
region_df = age_filter.copy()
region_df

,2024.07 월,2008 년,2009 년,2010 년,2011 년,2012 년,2013 년,2014 년,2015 년,2016 년,2017 년,2018 년,2019 년,2020 년,2021 년,2022 년,2023 년
행정구역(시군구)별,,,,,,,,,,,,,,,,,
강원특별자치도,144209,231065.0,225409.0,218742.0,211496.0,203750,197289,189716,182164,175986,169850,163512,158292,154953,152567,149922,146225
경기도,1544274,1942889.0,1909584.0,1875660.0,1821995.0,1773344,1737086,1696658,1654342,1628738,1607290,1588365,1572292,1575249,1578287,1569408,1557472
경상남도,364138,530537.0,516568.0,500941.0,482613.0,464182,450650,436152,421520,410837,402640,393373,385946,383247,380786,375634,369245
경상북도,249044,390102.0,376805.0,362451.0,348805.0,334403,322583,310248,297976,289410,281277,272783,266874,263717,261927,258260,252275
광주광역시,166571,267449.0,262840.0,255619.0,246632.0,237455,229172,220779,211064,203076,195934,188540,182693,179217,175490,172486,169143
대구광역시,246488,413520.0,400190.0,384389.0,367327.0,349858,334730,319583,304204,293254,283141,272310,263243,258394,253438,250655,248781
대전광역시,154742,257438.0,250396.0,242895.0,235026.0,226564,219845,211463,200364,192653,185194,177566,171479,167548,163758,160384,157316
부산광역시,308901,510171.0,488489.0,464020.0,438842.0,415731,397544,379620,363614,350942,339422,329416,321577,318814,316351,314084,311374
서울특별시,816760,1430369.0,1383032.0,1328655.0,1265512.0,1203387,1153658,1106972,1055543,1012122,975749,935112,908043,888503,866291,847058,829704
세종특별자치시,65065,0.0,0.0,0.0,0.0,14853,16112,21705,31352,36787,43270,49248,53676,57006,60306,63237,64630
울산광역시,128905,201868.0,194048.0,185889.0,177696.0,169975,163459,157358,151163,146442,142045,138118,135225,134384,133098,132100,130447
인천광역시,317310,448432.0,433572.0,417376.0,401980.0,388190,377931,366826,355648,347667,339919,331617,325166,321283,319584,319348,318966
전국,5348678,7872603.0,7660206.0,7421479.0,7143803.0,6875773,6662444,6445006,6221904,6055963,5911931,5760986,5643302,5589556,5540736,5479672,5408913
전라남도,178488,294267.0,285126.0,274115.0,262916.0,251525,241760,232156,222914,215734,208827,201351,195127,191170,188443,185073,181396
전북특별자치도,181191,298909.0,291159.0,282128.0,271967.0,260920,251906,242451,233051,225160,217936,209514,202377,197878,194021,189392,184643
제주특별자치도,82953,99134.0,97435.0,95168.0,92616.0,90333,88993,87507,86312,85886,85794,85057,84108,84639,85063,84943,84005
충청남도,234008,310291.0,305152.0,299842.0,292935.0,274400,269565,263346,256498,252448,249956,245999,241935,240101,239359,237879,235934
충청북도,165631,246162.0,240401.0,233589.0,225445.0,216903,210161,202466,194175,188821,183687,179105,175249,173453,171967,169809,167357

In [10]:
region_df = region_df.transpose()
region_df

행정구역(시군구)별,강원특별자치도,경기도,경상남도,경상북도,광주광역시,대구광역시,대전광역시,부산광역시,서울특별시,세종특별자치시,울산광역시,인천광역시,전국,전라남도,전북특별자치도,제주특별자치도,충청남도,충청북도
2024.07 월,144209.0,1544274.0,364138.0,249044.0,166571.0,246488.0,154742.0,308901.0,816760.0,65065.0,128905.0,317310.0,5348678.0,178488.0,181191.0,82953.0,234008.0,165631.0
2008 년,231065.0,1942889.0,530537.0,390102.0,267449.0,413520.0,257438.0,510171.0,1430369.0,0.0,201868.0,448432.0,7872603.0,294267.0,298909.0,99134.0,310291.0,246162.0
2009 년,225409.0,1909584.0,516568.0,376805.0,262840.0,400190.0,250396.0,488489.0,1383032.0,0.0,194048.0,433572.0,7660206.0,285126.0,291159.0,97435.0,305152.0,240401.0
2010 년,218742.0,1875660.0,500941.0,362451.0,255619.0,384389.0,242895.0,464020.0,1328655.0,0.0,185889.0,417376.0,7421479.0,274115.0,282128.0,95168.0,299842.0,233589.0
2011 년,211496.0,1821995.0,482613.0,348805.0,246632.0,367327.0,235026.0,438842.0,1265512.0,0.0,177696.0,401980.0,7143803.0,262916.0,271967.0,92616.0,292935.0,225445.0
2012 년,203750.0,1773344.0,464182.0,334403.0,237455.0,349858.0,226564.0,415731.0,1203387.0,14853.0,169975.0,388190.0,6875773.0,251525.0,260920.0,90333.0,274400.0,216903.0
2013 년,197289.0,1737086.0,450650.0,322583.0,229172.0,334730.0,219845.0,397544.0,1153658.0,16112.0,163459.0,377931.0,6662444.0,241760.0,251906.0,88993.0,269565.0,210161.0
2014 년,189716.0,1696658.0,436152.0,310248.0,220779.0,319583.0,211463.0,379620.0,1106972.0,21705.0,157358.0,366826.0,6445006.0,232156.0,242451.0,87507.0,263346.0,202466.0
2015 년,182164.0,1654342.0,421520.0,297976.0,211064.0,304204.0,200364.0,363614.0,1055543.0,31352.0,151163.0,355648.0,6221904.0,222914.0,233051.0,86312.0,256498.0,194175.0
2016 년,175986.0,1628738.0,410837.0,289410.0,203076.0,293254.0,192653.0,350942.0,1012122.0,36787.0,146442.0,347667.0,6055963.0,215734.0,225160.0,85886.0,252448.0,188821.0
2017 년,169850.0,1607290.0,402640.0,281277.0,195934.0,283141.0,185194.0,339422.0,975749.0,43270.0,142045.0,339919.0,5911931.0,208827.0,217936.0,85794.0,249956.0,183687.0
2018 년,163512.0,1588365.0,393373.0,272783.0,188540.0,272310.0,177566.0,329416.0,935112.0,49248.0,138118.0,331617.0,5760986.0,201351.0,209514.0,85057.0,245999.0,179105.0
2019 년,158292.0,1572292.0,385946.0,266874.0,182693.0,263243.0,171479.0,321577.0,908043.0,53676.0,135225.0,325166.0,5643302.0,195127.0,202377.0,84108.0,241935.0,175249.0
2020 년,154953.0,1575249.0,383247.0,263717.0,179217.0,258394.0,167548.0,318814.0,888503.0,57006.0,134384.0,321283.0,5589556.0,191170.0,197878.0,84639.0,240101.0,173453.0
2021 년,152567.0,1578287.0,380786.0,261927.0,175490.0,253438.0,163758.0,316351.0,866291.0,60306.0,133098.0,319584.0,5540736.0,188443.0,194021.0,85063.0,239359.0,171967.0
2022 년,149922.0,1569408.0,375634.0,258260.0,172486.0,250655.0,160384.0,314084.0,847058.0,63237.0,132100.0,319348.0,5479672.0,185073.0,189392.0,84943.0,237879.0,169809.0
2023 년,146225.0,1557472.0,369245.0,252275.0,169143.0,248781.0,157316.0,311374.0,829704.0,64630.0,130447.0,318966.0,5408913.0,181396.0,184643.0,84005.0,235934.0,167357.0

In [11]:
region_df.columns

Index(['강원특별자치도', '경기도', '경상남도', '경상북도', '광주광역시', '대구광역시', '대전광역시', '부산광역시',
       '서울특별시', '세종특별자치시', '울산광역시', '인천광역시', '전국', '전라남도', '전북특별자치도',
       '제주특별자치도', '충청남도', '충청북도'],
      dtype='object', name='행정구역(시군구)별')

In [12]:
# 인덱스의 name 속성 없애기
region_df.index = region_df.index.rename(None)
region_df

행정구역(시군구)별,강원특별자치도,경기도,경상남도,경상북도,광주광역시,대구광역시,대전광역시,부산광역시,서울특별시,세종특별자치시,울산광역시,인천광역시,전국,전라남도,전북특별자치도,제주특별자치도,충청남도,충청북도
2024.07 월,144209.0,1544274.0,364138.0,249044.0,166571.0,246488.0,154742.0,308901.0,816760.0,65065.0,128905.0,317310.0,5348678.0,178488.0,181191.0,82953.0,234008.0,165631.0
2008 년,231065.0,1942889.0,530537.0,390102.0,267449.0,413520.0,257438.0,510171.0,1430369.0,0.0,201868.0,448432.0,7872603.0,294267.0,298909.0,99134.0,310291.0,246162.0
2009 년,225409.0,1909584.0,516568.0,376805.0,262840.0,400190.0,250396.0,488489.0,1383032.0,0.0,194048.0,433572.0,7660206.0,285126.0,291159.0,97435.0,305152.0,240401.0
2010 년,218742.0,1875660.0,500941.0,362451.0,255619.0,384389.0,242895.0,464020.0,1328655.0,0.0,185889.0,417376.0,7421479.0,274115.0,282128.0,95168.0,299842.0,233589.0
2011 년,211496.0,1821995.0,482613.0,348805.0,246632.0,367327.0,235026.0,438842.0,1265512.0,0.0,177696.0,401980.0,7143803.0,262916.0,271967.0,92616.0,292935.0,225445.0
2012 년,203750.0,1773344.0,464182.0,334403.0,237455.0,349858.0,226564.0,415731.0,1203387.0,14853.0,169975.0,388190.0,6875773.0,251525.0,260920.0,90333.0,274400.0,216903.0
2013 년,197289.0,1737086.0,450650.0,322583.0,229172.0,334730.0,219845.0,397544.0,1153658.0,16112.0,163459.0,377931.0,6662444.0,241760.0,251906.0,88993.0,269565.0,210161.0
2014 년,189716.0,1696658.0,436152.0,310248.0,220779.0,319583.0,211463.0,379620.0,1106972.0,21705.0,157358.0,366826.0,6445006.0,232156.0,242451.0,87507.0,263346.0,202466.0
2015 년,182164.0,1654342.0,421520.0,297976.0,211064.0,304204.0,200364.0,363614.0,1055543.0,31352.0,151163.0,355648.0,6221904.0,222914.0,233051.0,86312.0,256498.0,194175.0
2016 년,175986.0,1628738.0,410837.0,289410.0,203076.0,293254.0,192653.0,350942.0,1012122.0,36787.0,146442.0,347667.0,6055963.0,215734.0,225160.0,85886.0,252448.0,188821.0
2017 년,169850.0,1607290.0,402640.0,281277.0,195934.0,283141.0,185194.0,339422.0,975749.0,43270.0,142045.0,339919.0,5911931.0,208827.0,217936.0,85794.0,249956.0,183687.0
2018 년,163512.0,1588365.0,393373.0,272783.0,188540.0,272310.0,177566.0,329416.0,935112.0,49248.0,138118.0,331617.0,5760986.0,201351.0,209514.0,85057.0,245999.0,179105.0
2019 년,158292.0,1572292.0,385946.0,266874.0,182693.0,263243.0,171479.0,321577.0,908043.0,53676.0,135225.0,325166.0,5643302.0,195127.0,202377.0,84108.0,241935.0,175249.0
2020 년,154953.0,1575249.0,383247.0,263717.0,179217.0,258394.0,167548.0,318814.0,888503.0,57006.0,134384.0,321283.0,5589556.0,191170.0,197878.0,84639.0,240101.0,173453.0
2021 년,152567.0,1578287.0,380786.0,261927.0,175490.0,253438.0,163758.0,316351.0,866291.0,60306.0,133098.0,319584.0,5540736.0,188443.0,194021.0,85063.0,239359.0,171967.0
2022 년,149922.0,1569408.0,375634.0,258260.0,172486.0,250655.0,160384.0,314084.0,847058.0,63237.0,132100.0,319348.0,5479672.0,185073.0,189392.0,84943.0,237879.0,169809.0
2023 년,146225.0,1557472.0,369245.0,252275.0,169143.0,248781.0,157316.0,311374.0,829704.0,64630.0,130447.0,318966.0,5408913.0,181396.0,184643.0,84005.0,235934.0,167357.0

In [13]:
# 인덱스 이름 제거
region_df.rename_axis(None, inplace=True)

# 'index' 열의 이름을 '연도'로 변경
region_df.rename(columns={'index': '연도'}, inplace=True)

region_df

행정구역(시군구)별,강원특별자치도,경기도,경상남도,경상북도,광주광역시,대구광역시,대전광역시,부산광역시,서울특별시,세종특별자치시,울산광역시,인천광역시,전국,전라남도,전북특별자치도,제주특별자치도,충청남도,충청북도
2024.07 월,144209.0,1544274.0,364138.0,249044.0,166571.0,246488.0,154742.0,308901.0,816760.0,65065.0,128905.0,317310.0,5348678.0,178488.0,181191.0,82953.0,234008.0,165631.0
2008 년,231065.0,1942889.0,530537.0,390102.0,267449.0,413520.0,257438.0,510171.0,1430369.0,0.0,201868.0,448432.0,7872603.0,294267.0,298909.0,99134.0,310291.0,246162.0
2009 년,225409.0,1909584.0,516568.0,376805.0,262840.0,400190.0,250396.0,488489.0,1383032.0,0.0,194048.0,433572.0,7660206.0,285126.0,291159.0,97435.0,305152.0,240401.0
2010 년,218742.0,1875660.0,500941.0,362451.0,255619.0,384389.0,242895.0,464020.0,1328655.0,0.0,185889.0,417376.0,7421479.0,274115.0,282128.0,95168.0,299842.0,233589.0
2011 년,211496.0,1821995.0,482613.0,348805.0,246632.0,367327.0,235026.0,438842.0,1265512.0,0.0,177696.0,401980.0,7143803.0,262916.0,271967.0,92616.0,292935.0,225445.0
2012 년,203750.0,1773344.0,464182.0,334403.0,237455.0,349858.0,226564.0,415731.0,1203387.0,14853.0,169975.0,388190.0,6875773.0,251525.0,260920.0,90333.0,274400.0,216903.0
2013 년,197289.0,1737086.0,450650.0,322583.0,229172.0,334730.0,219845.0,397544.0,1153658.0,16112.0,163459.0,377931.0,6662444.0,241760.0,251906.0,88993.0,269565.0,210161.0
2014 년,189716.0,1696658.0,436152.0,310248.0,220779.0,319583.0,211463.0,379620.0,1106972.0,21705.0,157358.0,366826.0,6445006.0,232156.0,242451.0,87507.0,263346.0,202466.0
2015 년,182164.0,1654342.0,421520.0,297976.0,211064.0,304204.0,200364.0,363614.0,1055543.0,31352.0,151163.0,355648.0,6221904.0,222914.0,233051.0,86312.0,256498.0,194175.0
2016 년,175986.0,1628738.0,410837.0,289410.0,203076.0,293254.0,192653.0,350942.0,1012122.0,36787.0,146442.0,347667.0,6055963.0,215734.0,225160.0,85886.0,252448.0,188821.0
2017 년,169850.0,1607290.0,402640.0,281277.0,195934.0,283141.0,185194.0,339422.0,975749.0,43270.0,142045.0,339919.0,5911931.0,208827.0,217936.0,85794.0,249956.0,183687.0
2018 년,163512.0,1588365.0,393373.0,272783.0,188540.0,272310.0,177566.0,329416.0,935112.0,49248.0,138118.0,331617.0,5760986.0,201351.0,209514.0,85057.0,245999.0,179105.0
2019 년,158292.0,1572292.0,385946.0,266874.0,182693.0,263243.0,171479.0,321577.0,908043.0,53676.0,135225.0,325166.0,5643302.0,195127.0,202377.0,84108.0,241935.0,175249.0
2020 년,154953.0,1575249.0,383247.0,263717.0,179217.0,258394.0,167548.0,318814.0,888503.0,57006.0,134384.0,321283.0,5589556.0,191170.0,197878.0,84639.0,240101.0,173453.0
2021 년,152567.0,1578287.0,380786.0,261927.0,175490.0,253438.0,163758.0,316351.0,866291.0,60306.0,133098.0,319584.0,5540736.0,188443.0,194021.0,85063.0,239359.0,171967.0
2022 년,149922.0,1569408.0,375634.0,258260.0,172486.0,250655.0,160384.0,314084.0,847058.0,63237.0,132100.0,319348.0,5479672.0,185073.0,189392.0,84943.0,237879.0,169809.0
2023 년,146225.0,1557472.0,369245.0,252275.0,169143.0,248781.0,157316.0,311374.0,829704.0,64630.0,130447.0,318966.0,5408913.0,181396.0,184643.0,84005.0,235934.0,167357.0

In [14]:
# 첫 행을 연도로 설정
region_df.columns.name = None
region_df = region_df.rename_axis('연도').reset_index()
region_df

,연도,강원특별자치도,경기도,경상남도,경상북도,광주광역시,대구광역시,대전광역시,부산광역시,서울특별시,세종특별자치시,울산광역시,인천광역시,전국,전라남도,전북특별자치도,제주특별자치도,충청남도,충청북도
0,2024.07 월,144209.0,1544274.0,364138.0,249044.0,166571.0,246488.0,154742.0,308901.0,816760.0,65065.0,128905.0,317310.0,5348678.0,178488.0,181191.0,82953.0,234008.0,165631.0
1,2008 년,231065.0,1942889.0,530537.0,390102.0,267449.0,413520.0,257438.0,510171.0,1430369.0,0.0,201868.0,448432.0,7872603.0,294267.0,298909.0,99134.0,310291.0,246162.0
2,2009 년,225409.0,1909584.0,516568.0,376805.0,262840.0,400190.0,250396.0,488489.0,1383032.0,0.0,194048.0,433572.0,7660206.0,285126.0,291159.0,97435.0,305152.0,240401.0
3,2010 년,218742.0,1875660.0,500941.0,362451.0,255619.0,384389.0,242895.0,464020.0,1328655.0,0.0,185889.0,417376.0,7421479.0,274115.0,282128.0,95168.0,299842.0,233589.0
4,2011 년,211496.0,1821995.0,482613.0,348805.0,246632.0,367327.0,235026.0,438842.0,1265512.0,0.0,177696.0,401980.0,7143803.0,262916.0,271967.0,92616.0,292935.0,225445.0
5,2012 년,203750.0,1773344.0,464182.0,334403.0,237455.0,349858.0,226564.0,415731.0,1203387.0,14853.0,169975.0,388190.0,6875773.0,251525.0,260920.0,90333.0,274400.0,216903.0
6,2013 년,197289.0,1737086.0,450650.0,322583.0,229172.0,334730.0,219845.0,397544.0,1153658.0,16112.0,163459.0,377931.0,6662444.0,241760.0,251906.0,88993.0,269565.0,210161.0
7,2014 년,189716.0,1696658.0,436152.0,310248.0,220779.0,319583.0,211463.0,379620.0,1106972.0,21705.0,157358.0,366826.0,6445006.0,232156.0,242451.0,87507.0,263346.0,202466.0
8,2015 년,182164.0,1654342.0,421520.0,297976.0,211064.0,304204.0,200364.0,363614.0,1055543.0,31352.0,151163.0,355648.0,6221904.0,222914.0,233051.0,86312.0,256498.0,194175.0
9,2016 년,175986.0,1628738.0,410837.0,289410.0,203076.0,293254.0,192653.0,350942.0,1012122.0,36787.0,146442.0,347667.0,6055963.0,215734.0,225160.0,85886.0,252448.0,188821.0
10,2017 년,169850.0,1607290.0,402640.0,281277.0,195934.0,283141.0,185194.0,339422.0,975749.0,43270.0,142045.0,339919.0,5911931.0,208827.0,217936.0,85794.0,249956.0,183687.0
11,2018 년,163512.0,1588365.0,393373.0,272783.0,188540.0,272310.0,177566.0,329416.0,935112.0,49248.0,138118.0,331617.0,5760986.0,201351.0,209514.0,85057.0,245999.0,179105.0
12,2019 년,158292.0,1572292.0,385946.0,266874.0,182693.0,263243.0,171479.0,321577.0,908043.0,53676.0,135225.0,325166.0,5643302.0,195127.0,202377.0,84108.0,241935.0,175249.0
13,2020 년,154953.0,1575249.0,383247.0,263717.0,179217.0,258394.0,167548.0,318814.0,888503.0,57006.0,134384.0,321283.0,5589556.0,191170.0,197878.0,84639.0,240101.0,173453.0
14,2021 년,152567.0,1578287.0,380786.0,261927.0,175490.0,253438.0,163758.0,316351.0,866291.0,60306.0,133098.0,319584.0,5540736.0,188443.0,194021.0,85063.0,239359.0,171967.0
15,2022 년,149922.0,1569408.0,375634.0,258260.0,172486.0,250655.0,160384.0,314084.0,847058.0,63237.0,132100.0,319348.0,5479672.0,185073.0,189392.0,84943.0,237879.0,169809.0
16,2023 년,146225.0,1557472.0,369245.0,252275.0,169143.0,248781.0,157316.0,311374.0,829704.0,64630.0,130447.0,318966.0,5408913.0,181396.0,184643.0,84005.0,235934.0,167357.0

In [15]:
region_df.columns
region_df.index

RangeIndex(start=0, stop=17, step=1)

In [16]:
# '연도' 컬럼을 인덱스로 설정
region_df.set_index('연도', inplace=True)
region_df

,강원특별자치도,경기도,경상남도,경상북도,광주광역시,대구광역시,대전광역시,부산광역시,서울특별시,세종특별자치시,울산광역시,인천광역시,전국,전라남도,전북특별자치도,제주특별자치도,충청남도,충청북도
연도,,,,,,,,,,,,,,,,,,
2024.07 월,144209.0,1544274.0,364138.0,249044.0,166571.0,246488.0,154742.0,308901.0,816760.0,65065.0,128905.0,317310.0,5348678.0,178488.0,181191.0,82953.0,234008.0,165631.0
2008 년,231065.0,1942889.0,530537.0,390102.0,267449.0,413520.0,257438.0,510171.0,1430369.0,0.0,201868.0,448432.0,7872603.0,294267.0,298909.0,99134.0,310291.0,246162.0
2009 년,225409.0,1909584.0,516568.0,376805.0,262840.0,400190.0,250396.0,488489.0,1383032.0,0.0,194048.0,433572.0,7660206.0,285126.0,291159.0,97435.0,305152.0,240401.0
2010 년,218742.0,1875660.0,500941.0,362451.0,255619.0,384389.0,242895.0,464020.0,1328655.0,0.0,185889.0,417376.0,7421479.0,274115.0,282128.0,95168.0,299842.0,233589.0
2011 년,211496.0,1821995.0,482613.0,348805.0,246632.0,367327.0,235026.0,438842.0,1265512.0,0.0,177696.0,401980.0,7143803.0,262916.0,271967.0,92616.0,292935.0,225445.0
2012 년,203750.0,1773344.0,464182.0,334403.0,237455.0,349858.0,226564.0,415731.0,1203387.0,14853.0,169975.0,388190.0,6875773.0,251525.0,260920.0,90333.0,274400.0,216903.0
2013 년,197289.0,1737086.0,450650.0,322583.0,229172.0,334730.0,219845.0,397544.0,1153658.0,16112.0,163459.0,377931.0,6662444.0,241760.0,251906.0,88993.0,269565.0,210161.0
2014 년,189716.0,1696658.0,436152.0,310248.0,220779.0,319583.0,211463.0,379620.0,1106972.0,21705.0,157358.0,366826.0,6445006.0,232156.0,242451.0,87507.0,263346.0,202466.0
2015 년,182164.0,1654342.0,421520.0,297976.0,211064.0,304204.0,200364.0,363614.0,1055543.0,31352.0,151163.0,355648.0,6221904.0,222914.0,233051.0,86312.0,256498.0,194175.0
2016 년,175986.0,1628738.0,410837.0,289410.0,203076.0,293254.0,192653.0,350942.0,1012122.0,36787.0,146442.0,347667.0,6055963.0,215734.0,225160.0,85886.0,252448.0,188821.0
2017 년,169850.0,1607290.0,402640.0,281277.0,195934.0,283141.0,185194.0,339422.0,975749.0,43270.0,142045.0,339919.0,5911931.0,208827.0,217936.0,85794.0,249956.0,183687.0
2018 년,163512.0,1588365.0,393373.0,272783.0,188540.0,272310.0,177566.0,329416.0,935112.0,49248.0,138118.0,331617.0,5760986.0,201351.0,209514.0,85057.0,245999.0,179105.0
2019 년,158292.0,1572292.0,385946.0,266874.0,182693.0,263243.0,171479.0,321577.0,908043.0,53676.0,135225.0,325166.0,5643302.0,195127.0,202377.0,84108.0,241935.0,175249.0
2020 년,154953.0,1575249.0,383247.0,263717.0,179217.0,258394.0,167548.0,318814.0,888503.0,57006.0,134384.0,321283.0,5589556.0,191170.0,197878.0,84639.0,240101.0,173453.0
2021 년,152567.0,1578287.0,380786.0,261927.0,175490.0,253438.0,163758.0,316351.0,866291.0,60306.0,133098.0,319584.0,5540736.0,188443.0,194021.0,85063.0,239359.0,171967.0
2022 년,149922.0,1569408.0,375634.0,258260.0,172486.0,250655.0,160384.0,314084.0,847058.0,63237.0,132100.0,319348.0,5479672.0,185073.0,189392.0,84943.0,237879.0,169809.0
2023 년,146225.0,1557472.0,369245.0,252275.0,169143.0,248781.0,157316.0,311374.0,829704.0,64630.0,130447.0,318966.0,5408913.0,181396.0,184643.0,84005.0,235934.0,167357.0

In [17]:
# 아동1 지역 리스트
child1_regions = ['강원특별자치도','경상남도','경상북도','전라남도','전북특별자치도','충청남도','충청북도']

# 아동1 컬럼 합치기
region_df['아동1'] = region_df[child1_regions].sum(axis=1)

# 아동2 지역 리스트 (아동1, '전체국민' 제외)
child2_regions = [region for region in region_df.columns if region not in child1_regions + ['전국']]

# 아동2 컬럼 합치기 전에 숫자형으로 변환
region_df[child2_regions] = region_df[child2_regions].apply(pd.to_numeric, errors='coerce')
region_df['아동2'] = region_df[child2_regions].sum(axis=1)

# 필요한 컬럼만 저장
#region_df = region_df[['연도','전국', '아동1', '아동2']]
region_df = region_df[['전국', '아동1', '아동2']]

region_df

                  전국        아동1        아동2
연도
2024.07 월  5348678.0  1516709.0  5348678.0
2008 년     7872603.0  2301333.0  7872603.0
2009 년     7660206.0  2240620.0  7660206.0
2010 년     7421479.0  2171808.0  7421479.0
2011 년     7143803.0  2096177.0  7143803.0
2012 년     6875773.0  2006083.0  6875773.0
2013 년     6662444.0  1943914.0  6662444.0
2014 년     6445006.0  1876535.0  6445006.0
2015 년     6221904.0  1808298.0  6221904.0
2016 년     6055963.0  1758396.0  6055963.0
2017 년     5911931.0  1714173.0  5911931.0
2018 년     5760986.0  1665637.0  5760986.0
2019 년     5643302.0  1625800.0  5643302.0
2020 년     5589556.0  1604519.0  5589556.0
2021 년     5540736.0  1589070.0  5540736.0
2022 년     5479672.0  1565969.0  5479672.0
2023 년     5408913.0  1537075.0  5408913.0

In [18]:
region_df

                  전국        아동1        아동2
연도
2024.07 월  5348678.0  1516709.0  5348678.0
2008 년     7872603.0  2301333.0  7872603.0
2009 년     7660206.0  2240620.0  7660206.0
2010 년     7421479.0  2171808.0  7421479.0
2011 년     7143803.0  2096177.0  7143803.0
2012 년     6875773.0  2006083.0  6875773.0
2013 년     6662444.0  1943914.0  6662444.0
2014 년     6445006.0  1876535.0  6445006.0
2015 년     6221904.0  1808298.0  6221904.0
2016 년     6055963.0  1758396.0  6055963.0
2017 년     5911931.0  1714173.0  5911931.0
2018 년     5760986.0  1665637.0  5760986.0
2019 년     5643302.0  1625800.0  5643302.0
2020 년     5589556.0  1604519.0  5589556.0
2021 년     5540736.0  1589070.0  5540736.0
2022 년     5479672.0  1565969.0  5479672.0
2023 년     5408913.0  1537075.0  5408913.0

# 4. index 연도 int형으로 바꿔주기

In [19]:
int_df = region_df.copy()
int_df

                  전국        아동1        아동2
연도
2024.07 월  5348678.0  1516709.0  5348678.0
2008 년     7872603.0  2301333.0  7872603.0
2009 년     7660206.0  2240620.0  7660206.0
2010 년     7421479.0  2171808.0  7421479.0
2011 년     7143803.0  2096177.0  7143803.0
2012 년     6875773.0  2006083.0  6875773.0
2013 년     6662444.0  1943914.0  6662444.0
2014 년     6445006.0  1876535.0  6445006.0
2015 년     6221904.0  1808298.0  6221904.0
2016 년     6055963.0  1758396.0  6055963.0
2017 년     5911931.0  1714173.0  5911931.0
2018 년     5760986.0  1665637.0  5760986.0
2019 년     5643302.0  1625800.0  5643302.0
2020 년     5589556.0  1604519.0  5589556.0
2021 년     5540736.0  1589070.0  5540736.0
2022 년     5479672.0  1565969.0  5479672.0
2023 년     5408913.0  1537075.0  5408913.0

In [20]:
# 인덱스를 컬럼으로 변환
int_df = int_df.reset_index()

# '연도' 컬럼에서 숫자 부분만 추출하고 정수형으로 변환
int_df['연도'] = int_df['연도'].str.extract(r'(\d{4})').astype(int)

# 변경된 '연도' 컬럼을 다시 인덱스로 설정
int_df = int_df.set_index('연도')

In [ ]:
int_df

             전국        아동1        아동2
연도
2024  5790242.0  1642923.0  5790242.0
2008  8510588.0  2484723.0  8510588.0
2009  8360727.0  2438974.0  8360727.0
2010  8147076.0  2378229.0  8147076.0
2011  7854617.0  2300548.0  7854617.0
2012  7589751.0  2210398.0  7589751.0
2013  7370691.0  2148574.0  7370691.0
2014  7130507.0  2077425.0  7130507.0
2015  6893407.0  2005404.0  6893407.0
2016  6695799.0  1946985.0  6695799.0
2017  6531675.0  1897143.0  6531675.0
2018  6399567.0  1852851.0  6399567.0
2019  6202006.0  1790145.0  6202006.0
2020  6083600.0  1748950.0  6083600.0
2021  6033002.0  1729912.0  6033002.0
2022  5952294.0  1701979.0  5952294.0
2023  5843938.0  1662926.0  5843938.0

In [ ]:
# CSV 파일로 저장 (UTF-8 인코딩)
csv_filename = '인구전처리_1차.csv'
int_df.to_csv(csv_filename, encoding='utf-8')

# 파일 다운로드
files.download(csv_filename)

In [21]:
# CSV 파일로 저장 (cp949 인코딩)
csv_filename = '인구전처리_1차(~17세).csv'
int_df.to_csv(csv_filename, encoding='cp949')

# 파일 다운로드
files.download(csv_filename)