<a href="https://colab.research.google.com/github/LYZAcell/data_study/blob/main/%EC%9D%B8%EA%B5%AC%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%A0%84%EC%B2%98%EB%A6%AC2_0819.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
from google.colab import files

# 1. df transpose전 (실행 쭉쭉)

In [2]:
df = pd.read_csv('./행정구역_연도별_총주민등록인구.csv', encoding='euc-kr')
df.head()

,행정구역(시군구)별,연령별,항목,단위,2024.07 월,2008 년,2009 년,2010 년,2011 년,2012 년,...,2015 년,2016 년,2017 년,2018 년,2019 년,2020 년,2021 년,2022 년,2023 년,Unnamed: 21
0,전국,계,총인구수[명],명,51265238,49540367.0,49773145.0,50515666.0,50734284.0,50948272,...,51529338,51696216,51778544,51826059,51849861,51829023,51638809,51439038,51325329,NaN
1,전국,계,남자인구수[명],명,25528507,24822897.0,24929939.0,25310385.0,25406934.0,25504060,...,25758186,25827594,25855919,25866129,25864816,25841029,25746684,25636951,25565736,NaN
2,전국,계,여자인구수[명],명,25736731,24717470.0,24843206.0,25205281.0,25327350.0,25444212,...,25771152,25868622,25922625,25959930,25985045,25987994,25892125,25802087,25759593,NaN
3,전국,0세,총인구수[명],명,223834,444421.0,424529.0,448516.0,451579.0,464374,...,424563,393674,345786,317685,295132,265087,253946,244250,225958,NaN
4,전국,0세,남자인구수[명],명,114623,228977.0,218756.0,231521.0,231954.0,238639,...,217775,201541,178138,162950,151494,135661,130157,124860,115707,NaN

In [3]:
# 열 이름 필터링
cols_age = ['연령별', '6세','7세','8세','9세','10세','11세','12세','13세','14세','15세','16세','17세','18세']

# 필터링 후 인덱스 리스트로 만들기
drop_index = df[~df['연령별'].isin(cols_age)].index

# 해당 인덱스 드롭하기
df_filtered = df.drop(drop_index)

df_filtered

,행정구역(시군구)별,연령별,항목,단위,2024.07 월,2008 년,2009 년,2010 년,2011 년,2012 년,...,2015 년,2016 년,2017 년,2018 년,2019 년,2020 년,2021 년,2022 년,2023 년,Unnamed: 21
21,전국,6세,총인구수[명],명,346359,494660.0,493040.0,473718.0,435724.0,449057,...,447817,473401,476061,489604,441362,440710,444555,413162,364740,NaN
22,전국,6세,남자인구수[명],명,177625,258531.0,256152.0,245698.0,225690.0,232273,...,230602,244059,244330,251225,226090,225736,227809,211336,187700,NaN
23,전국,6세,여자인구수[명],명,168734,236129.0,236888.0,228020.0,210034.0,216784,...,217215,229342,231731,238379,215272,214974,216746,201826,177040,NaN
24,전국,7세,총인구수[명],명,382519,559549.0,494611.0,493551.0,473970.0,435863,...,468546,448049,473580,476168,489772,441560,440866,444843,413535,NaN
25,전국,7세,남자인구수[명],명,196341,291499.0,258472.0,256412.0,245816.0,225763,...,241138,230694,244138,244333,251311,226161,225794,227921,211524,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5257,제주특별자치도,17세,남자인구수[명],명,3653,4110.0,4573.0,4462.0,4642.0,4571,...,4363,4327,4580,4112,3752,3733,3585,3434,3531,NaN
5258,제주특별자치도,17세,여자인구수[명],명,3438,3941.0,3884.0,4126.0,4142.0,4197,...,3910,3946,4328,3710,3235,3432,3194,3030,3229,NaN
5259,제주특별자치도,18세,총인구수[명],명,6378,6911.0,8015.0,8450.0,8546.0,8761,...,8715,8319,8304,8943,7827,6991,7153,6748,6425,NaN
5260,제주특별자치도,18세,남자인구수[명],명,3344,3742.0,4096.0,4572.0,4447.0,4631,...,4547,4391,4337,4592,4114,3758,3724,3579,3409,NaN
5261,제주특별자치도,18세,여자인구수[명],명,3034,3169.0,3919.0,3878.0,4099.0,4130,...,4168,3928,3967,4351,3713,3233,3429,3169,3016,NaN

In [4]:
age_filter = df_filtered.copy()
# '총인구수[명]' 항목만 선택
age_filter = age_filter[age_filter['항목'] == '총인구수[명]']

# 'Unnamed: 21' 열 제거
age_filter = age_filter.drop(columns=['Unnamed: 21'])
# 불필요한 컬럼제거
age_filter = age_filter.drop(columns=['단위','항목'])
age_filter.head(20)

,행정구역(시군구)별,연령별,2024.07 월,2008 년,2009 년,2010 년,2011 년,2012 년,2013 년,2014 년,2015 년,2016 년,2017 년,2018 년,2019 년,2020 년,2021 년,2022 년,2023 년
21,전국,6세,346359,494660.0,493040.0,473718.0,435724.0,449057,495221,468321,447817,473401,476061,489604,441362,440710,444555,413162,364740
24,전국,7세,382519,559549.0,494611.0,493551.0,473970.0,435863,449321,495536,468546,448049,473580,476168,489772,441560,440866,444843,413535
27,전국,8세,429673,639584.0,559360.0,495212.0,493658.0,474009,436031,449510,495761,468712,448183,473690,476358,489936,441672,441044,445099
30,전국,9세,447106,620098.0,639421.0,560067.0,495288.0,493679,474106,436172,449663,495918,468858,448251,473817,476474,490049,441805,441225
33,전국,10세,440406,640447.0,619828.0,640166.0,560042.0,495216,493745,474187,436313,449851,496041,468897,448401,473919,476536,490147,441952
36,전국,11세,464953,672419.0,640111.0,620740.0,640027.0,559908,495256,493804,474284,436439,449954,496074,469014,448450,473997,476573,490229
39,전국,12세,480200,686232.0,672065.0,641207.0,620650.0,639852,559931,495268,493916,474372,436496,449936,496146,469087,448481,473924,476570
42,전국,13세,489129,708751.0,685780.0,673228.0,640950.0,620407,639858,559938,495316,493970,474366,436420,449979,496175,469101,448369,473894
45,전국,14세,453461,714275.0,708234.0,687104.0,672862.0,640593,620395,639828,559996,495347,493910,474221,436418,449958,496081,468939,448324
48,전국,15세,456053,710578.0,713804.0,709686.0,686666.0,672396,640464,620320,639869,560014,495262,493626,474123,436320,449838,495811,468773
51,전국,16세,491136,724687.0,709953.0,715362.0,709218.0,686179,672216,640283,620297,639783,559804,494894,493389,473931,436095,449473,495547
54,전국,17세,467683,701323.0,723999.0,711438.0,714748.0,708614,685900,671839,640126,620107,639416,559205,494523,493036,473465,435582,449025
57,전국,18세,441564,637985.0,700521.0,725597.0,710814.0,713978,708247,685501,671503,639836,619744,638581,558704,494044,492266,472622,435025
327,서울특별시,6세,51970,88920.0,88847.0,85570.0,76678.0,78710,84583,79615,74176,77045,75386,76957,69031,68085,67581,62376,55100
330,서울특별시,7세,57136,97818.0,88001.0,87437.0,84286.0,75315,77366,83620,78271,72626,75929,73813,76160,68257,66923,66960,62036
333,서울특별시,8세,64604,112468.0,97286.0,87174.0,86520.0,83258,74650,76662,82452,76968,71772,74748,73259,75438,67174,66454,66691
336,서울특별시,9세,67209,108022.0,112236.0,96707.0,86398.0,85720,82595,74048,75752,81236,76157,70652,74305,72676,74480,66820,66430
339,서울특별시,10세,66167,112333.0,107794.0,111856.0,96006.0,85656,85082,82076,73327,75032,80577,75180,70378,73776,71911,74250,66672
342,서울특별시,11세,70356,118696.0,112499.0,107677.0,111428.0,95388,85239,84629,81332,72584,74502,79733,74930,70062,72979,71693,74287
345,서울특별시,12세,72593,122963.0,119523.0,113036.0,107708.0,111130,95197,85274,84334,80747,72380,74074,79942,74955,69798,73139,71911

In [5]:
# '행정구역(시군구)별'을 인덱스로 설정합니다.
age_filter_seoul = age_filter.set_index('행정구역(시군구)별')

# 이제 '서울특별시' 행을 가져올 수 있습니다.
age_filter_seoul.loc['서울특별시']

,연령별,2024.07 월,2008 년,2009 년,2010 년,2011 년,2012 년,2013 년,2014 년,2015 년,2016 년,2017 년,2018 년,2019 년,2020 년,2021 년,2022 년,2023 년
행정구역(시군구)별,,,,,,,,,,,,,,,,,,
서울특별시,6세,51970,88920.0,88847.0,85570.0,76678.0,78710,84583,79615,74176,77045,75386,76957,69031,68085,67581,62376,55100
서울특별시,7세,57136,97818.0,88001.0,87437.0,84286.0,75315,77366,83620,78271,72626,75929,73813,76160,68257,66923,66960,62036
서울특별시,8세,64604,112468.0,97286.0,87174.0,86520.0,83258,74650,76662,82452,76968,71772,74748,73259,75438,67174,66454,66691
서울특별시,9세,67209,108022.0,112236.0,96707.0,86398.0,85720,82595,74048,75752,81236,76157,70652,74305,72676,74480,66820,66430
서울특별시,10세,66167,112333.0,107794.0,111856.0,96006.0,85656,85082,82076,73327,75032,80577,75180,70378,73776,71911,74250,66672
서울특별시,11세,70356,118696.0,112499.0,107677.0,111428.0,95388,85239,84629,81332,72584,74502,79733,74930,70062,72979,71693,74287
서울특별시,12세,72593,122963.0,119523.0,113036.0,107708.0,111130,95197,85274,84334,80747,72380,74074,79942,74955,69798,73139,71911
서울특별시,13세,74049,128461.0,122857.0,119350.0,112316.0,106908,110486,94743,84511,83494,80264,71698,73725,79461,74226,69481,72773
서울특별시,14세,70046,132339.0,128767.0,123140.0,119063.0,111864,106669,110145,94302,83929,83081,79681,71582,73398,78965,73939,69371
서울특별시,15세,70736,133649.0,133249.0,129667.0,123169.0,118800,111753,106792,110050,93942,83791,82773,79677,71470,73101,78832,73898
서울특별시,16세,77241,138416.0,133501.0,133310.0,129002.0,122232,118196,111418,106085,109021,93326,83012,82287,79105,70668,72618,78204
서울특별시,17세,74653,136284.0,138472.0,133731.0,132938.0,128406,121842,117950,110951,105498,108584,92791,82767,81820,78485,70496,72331
서울특별시,18세,72396,125541.0,136108.0,138596.0,133113.0,132364,127962,121655,117610,110501,105344,108139,92621,82413,81354,78443,70353

In [6]:
# '행정구역(시군구)별' 열의 첫 번째 행의 값을 '전체국민'으로 변경
#age_filter.at[0, '행정구역(시군구)별'] = '전체국민'
#age_filter.loc['서울특별시']

In [7]:
age_filter

,행정구역(시군구)별,연령별,2024.07 월,2008 년,2009 년,2010 년,2011 년,2012 년,2013 년,2014 년,2015 년,2016 년,2017 년,2018 년,2019 년,2020 년,2021 년,2022 년,2023 년
21,전국,6세,346359,494660.0,493040.0,473718.0,435724.0,449057,495221,468321,447817,473401,476061,489604,441362,440710,444555,413162,364740
24,전국,7세,382519,559549.0,494611.0,493551.0,473970.0,435863,449321,495536,468546,448049,473580,476168,489772,441560,440866,444843,413535
27,전국,8세,429673,639584.0,559360.0,495212.0,493658.0,474009,436031,449510,495761,468712,448183,473690,476358,489936,441672,441044,445099
30,전국,9세,447106,620098.0,639421.0,560067.0,495288.0,493679,474106,436172,449663,495918,468858,448251,473817,476474,490049,441805,441225
33,전국,10세,440406,640447.0,619828.0,640166.0,560042.0,495216,493745,474187,436313,449851,496041,468897,448401,473919,476536,490147,441952
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5247,제주특별자치도,14세,6969,8851.0,8835.0,8663.0,8634.0,8183,8193,8785,7757,6993,7154,6815,6478,6822,7447,7018,6914
5250,제주특별자치도,15세,6955,8552.0,8739.0,8734.0,8639.0,8587,8156,8171,8797,7768,6988,7162,6788,6509,6834,7418,6984
5253,제주특별자치도,16세,7180,8493.0,8599.0,8791.0,8764.0,8653,8607,8201,8231,8848,7817,7002,7154,6794,6475,6772,7370
5256,제주특별자치도,17세,7091,8051.0,8457.0,8588.0,8784.0,8768,8674,8642,8273,8273,8908,7822,6987,7165,6779,6464,6760
5259,제주특별자치도,18세,6378,6911.0,8015.0,8450.0,8546.0,8761,8784,8662,8715,8319,8304,8943,7827,6991,7153,6748,6425

In [8]:
age_filter = age_filter.groupby('행정구역(시군구)별').sum()
age_filter = age_filter.drop(columns=['연령별'])
age_filter

,2024.07 월,2008 년,2009 년,2010 년,2011 년,2012 년,2013 년,2014 년,2015 년,2016 년,2017 년,2018 년,2019 년,2020 년,2021 년,2022 년,2023 년
행정구역(시군구)별,,,,,,,,,,,,,,,,,
강원특별자치도,156825,249804.0,245303.0,239441.0,231991.0,224263,217826,209953,202373,195374,188577,182563,175026,169981,166826,163762,158969
경기도,1668342,2089268.0,2074456.0,2048914.0,1993306.0,1947388,1911162,1865526,1822452,1791630,1767031,1755978,1720412,1708398,1712879,1699960,1678141
경상남도,393297,571890.0,562308.0,548028.0,529648.0,511366,497818,482788,466690,454038,444781,436234,423485,416356,413271,407191,398243
경상북도,269892,422669.0,411780.0,398611.0,383890.0,369490,357405,344193,331404,320682,312010,304331,294141,287388,285346,280364,273108
광주광역시,180717,287703.0,285310.0,279622.0,270235.0,261426,253579,244343,234548,225420,217369,210686,201884,195826,192240,187913,183266
대구광역시,266929,448435.0,438090.0,423185.0,404951.0,387819,372691,355790,339382,325740,314837,304589,291179,282322,277727,272948,269521
대전광역시,168161,278105.0,273050.0,266187.0,257718.0,249805,243058,233933,222210,213255,204839,197553,188948,182923,179025,175131,170503
부산광역시,333411,555978.0,538515.0,514954.0,487642.0,463716,443935,424359,405447,390530,376856,367206,354532,347400,344711,340703,335736
서울특별시,889156,1555910.0,1519140.0,1467251.0,1398625.0,1335751,1281620,1228627,1173153,1122623,1081093,1043251,1000664,970916,947645,925501,900057
세종특별자치시,69295,0.0,0.0,0.0,0.0,16144,17435,23212,33303,39060,45969,52481,56938,60412,64155,67302,68660
울산광역시,138862,218053.0,212393.0,204581.0,196070.0,188358,181838,174932,168376,162508,157402,153525,148579,145644,144490,142794,140462
인천광역시,343115,486368.0,475349.0,460535.0,444360.0,429852,419022,406191,394105,383843,375038,367447,356790,349179,348002,346372,344236
전국,5790242,8510588.0,8360727.0,8147076.0,7854617.0,7589751,7370691,7130507,6893407,6695799,6531675,6399567,6202006,6083600,6033002,5952294,5843938
전라남도,193469,317399.0,310142.0,300459.0,288542.0,277521,268253,257802,248299,239741,232265,225233,215790,209178,205778,201596,196448
전북특별자치도,197056,322718.0,316556.0,308735.0,298452.0,287972,278974,268797,258506,250080,241592,233771,223851,216799,212207,206753,200759
제주특별자치도,89331,106045.0,105450.0,103618.0,101162.0,99094,97777,96169,95027,94205,94098,94000,91935,91630,92216,91691,90430
충청남도,253159,334522.0,331484.0,327152.0,320275.0,300874,296151,289628,282600,277887,274606,271824,264953,260251,259441,257794,254523
충청북도,179225,265721.0,261401.0,255803.0,247750.0,238912,232147,224264,215532,209183,203312,198895,192899,188997,187043,184519,180876

# 3.지역별 groupby완료
- 아동1, 2 분리
-  컬럼맞추기

In [9]:
#복사
region_df = age_filter.copy()
region_df

,2024.07 월,2008 년,2009 년,2010 년,2011 년,2012 년,2013 년,2014 년,2015 년,2016 년,2017 년,2018 년,2019 년,2020 년,2021 년,2022 년,2023 년
행정구역(시군구)별,,,,,,,,,,,,,,,,,
강원특별자치도,156825,249804.0,245303.0,239441.0,231991.0,224263,217826,209953,202373,195374,188577,182563,175026,169981,166826,163762,158969
경기도,1668342,2089268.0,2074456.0,2048914.0,1993306.0,1947388,1911162,1865526,1822452,1791630,1767031,1755978,1720412,1708398,1712879,1699960,1678141
경상남도,393297,571890.0,562308.0,548028.0,529648.0,511366,497818,482788,466690,454038,444781,436234,423485,416356,413271,407191,398243
경상북도,269892,422669.0,411780.0,398611.0,383890.0,369490,357405,344193,331404,320682,312010,304331,294141,287388,285346,280364,273108
광주광역시,180717,287703.0,285310.0,279622.0,270235.0,261426,253579,244343,234548,225420,217369,210686,201884,195826,192240,187913,183266
대구광역시,266929,448435.0,438090.0,423185.0,404951.0,387819,372691,355790,339382,325740,314837,304589,291179,282322,277727,272948,269521
대전광역시,168161,278105.0,273050.0,266187.0,257718.0,249805,243058,233933,222210,213255,204839,197553,188948,182923,179025,175131,170503
부산광역시,333411,555978.0,538515.0,514954.0,487642.0,463716,443935,424359,405447,390530,376856,367206,354532,347400,344711,340703,335736
서울특별시,889156,1555910.0,1519140.0,1467251.0,1398625.0,1335751,1281620,1228627,1173153,1122623,1081093,1043251,1000664,970916,947645,925501,900057
세종특별자치시,69295,0.0,0.0,0.0,0.0,16144,17435,23212,33303,39060,45969,52481,56938,60412,64155,67302,68660
울산광역시,138862,218053.0,212393.0,204581.0,196070.0,188358,181838,174932,168376,162508,157402,153525,148579,145644,144490,142794,140462
인천광역시,343115,486368.0,475349.0,460535.0,444360.0,429852,419022,406191,394105,383843,375038,367447,356790,349179,348002,346372,344236
전국,5790242,8510588.0,8360727.0,8147076.0,7854617.0,7589751,7370691,7130507,6893407,6695799,6531675,6399567,6202006,6083600,6033002,5952294,5843938
전라남도,193469,317399.0,310142.0,300459.0,288542.0,277521,268253,257802,248299,239741,232265,225233,215790,209178,205778,201596,196448
전북특별자치도,197056,322718.0,316556.0,308735.0,298452.0,287972,278974,268797,258506,250080,241592,233771,223851,216799,212207,206753,200759
제주특별자치도,89331,106045.0,105450.0,103618.0,101162.0,99094,97777,96169,95027,94205,94098,94000,91935,91630,92216,91691,90430
충청남도,253159,334522.0,331484.0,327152.0,320275.0,300874,296151,289628,282600,277887,274606,271824,264953,260251,259441,257794,254523
충청북도,179225,265721.0,261401.0,255803.0,247750.0,238912,232147,224264,215532,209183,203312,198895,192899,188997,187043,184519,180876

In [10]:
region_df = region_df.transpose()
region_df

행정구역(시군구)별,강원특별자치도,경기도,경상남도,경상북도,광주광역시,대구광역시,대전광역시,부산광역시,서울특별시,세종특별자치시,울산광역시,인천광역시,전국,전라남도,전북특별자치도,제주특별자치도,충청남도,충청북도
2024.07 월,156825.0,1668342.0,393297.0,269892.0,180717.0,266929.0,168161.0,333411.0,889156.0,69295.0,138862.0,343115.0,5790242.0,193469.0,197056.0,89331.0,253159.0,179225.0
2008 년,249804.0,2089268.0,571890.0,422669.0,287703.0,448435.0,278105.0,555978.0,1555910.0,0.0,218053.0,486368.0,8510588.0,317399.0,322718.0,106045.0,334522.0,265721.0
2009 년,245303.0,2074456.0,562308.0,411780.0,285310.0,438090.0,273050.0,538515.0,1519140.0,0.0,212393.0,475349.0,8360727.0,310142.0,316556.0,105450.0,331484.0,261401.0
2010 년,239441.0,2048914.0,548028.0,398611.0,279622.0,423185.0,266187.0,514954.0,1467251.0,0.0,204581.0,460535.0,8147076.0,300459.0,308735.0,103618.0,327152.0,255803.0
2011 년,231991.0,1993306.0,529648.0,383890.0,270235.0,404951.0,257718.0,487642.0,1398625.0,0.0,196070.0,444360.0,7854617.0,288542.0,298452.0,101162.0,320275.0,247750.0
2012 년,224263.0,1947388.0,511366.0,369490.0,261426.0,387819.0,249805.0,463716.0,1335751.0,16144.0,188358.0,429852.0,7589751.0,277521.0,287972.0,99094.0,300874.0,238912.0
2013 년,217826.0,1911162.0,497818.0,357405.0,253579.0,372691.0,243058.0,443935.0,1281620.0,17435.0,181838.0,419022.0,7370691.0,268253.0,278974.0,97777.0,296151.0,232147.0
2014 년,209953.0,1865526.0,482788.0,344193.0,244343.0,355790.0,233933.0,424359.0,1228627.0,23212.0,174932.0,406191.0,7130507.0,257802.0,268797.0,96169.0,289628.0,224264.0
2015 년,202373.0,1822452.0,466690.0,331404.0,234548.0,339382.0,222210.0,405447.0,1173153.0,33303.0,168376.0,394105.0,6893407.0,248299.0,258506.0,95027.0,282600.0,215532.0
2016 년,195374.0,1791630.0,454038.0,320682.0,225420.0,325740.0,213255.0,390530.0,1122623.0,39060.0,162508.0,383843.0,6695799.0,239741.0,250080.0,94205.0,277887.0,209183.0
2017 년,188577.0,1767031.0,444781.0,312010.0,217369.0,314837.0,204839.0,376856.0,1081093.0,45969.0,157402.0,375038.0,6531675.0,232265.0,241592.0,94098.0,274606.0,203312.0
2018 년,182563.0,1755978.0,436234.0,304331.0,210686.0,304589.0,197553.0,367206.0,1043251.0,52481.0,153525.0,367447.0,6399567.0,225233.0,233771.0,94000.0,271824.0,198895.0
2019 년,175026.0,1720412.0,423485.0,294141.0,201884.0,291179.0,188948.0,354532.0,1000664.0,56938.0,148579.0,356790.0,6202006.0,215790.0,223851.0,91935.0,264953.0,192899.0
2020 년,169981.0,1708398.0,416356.0,287388.0,195826.0,282322.0,182923.0,347400.0,970916.0,60412.0,145644.0,349179.0,6083600.0,209178.0,216799.0,91630.0,260251.0,188997.0
2021 년,166826.0,1712879.0,413271.0,285346.0,192240.0,277727.0,179025.0,344711.0,947645.0,64155.0,144490.0,348002.0,6033002.0,205778.0,212207.0,92216.0,259441.0,187043.0
2022 년,163762.0,1699960.0,407191.0,280364.0,187913.0,272948.0,175131.0,340703.0,925501.0,67302.0,142794.0,346372.0,5952294.0,201596.0,206753.0,91691.0,257794.0,184519.0
2023 년,158969.0,1678141.0,398243.0,273108.0,183266.0,269521.0,170503.0,335736.0,900057.0,68660.0,140462.0,344236.0,5843938.0,196448.0,200759.0,90430.0,254523.0,180876.0

In [11]:
region_df.columns

Index(['강원특별자치도', '경기도', '경상남도', '경상북도', '광주광역시', '대구광역시', '대전광역시', '부산광역시',
       '서울특별시', '세종특별자치시', '울산광역시', '인천광역시', '전국', '전라남도', '전북특별자치도',
       '제주특별자치도', '충청남도', '충청북도'],
      dtype='object', name='행정구역(시군구)별')

In [12]:
# 인덱스의 name 속성 없애기
region_df.index = region_df.index.rename(None)
region_df

행정구역(시군구)별,강원특별자치도,경기도,경상남도,경상북도,광주광역시,대구광역시,대전광역시,부산광역시,서울특별시,세종특별자치시,울산광역시,인천광역시,전국,전라남도,전북특별자치도,제주특별자치도,충청남도,충청북도
2024.07 월,156825.0,1668342.0,393297.0,269892.0,180717.0,266929.0,168161.0,333411.0,889156.0,69295.0,138862.0,343115.0,5790242.0,193469.0,197056.0,89331.0,253159.0,179225.0
2008 년,249804.0,2089268.0,571890.0,422669.0,287703.0,448435.0,278105.0,555978.0,1555910.0,0.0,218053.0,486368.0,8510588.0,317399.0,322718.0,106045.0,334522.0,265721.0
2009 년,245303.0,2074456.0,562308.0,411780.0,285310.0,438090.0,273050.0,538515.0,1519140.0,0.0,212393.0,475349.0,8360727.0,310142.0,316556.0,105450.0,331484.0,261401.0
2010 년,239441.0,2048914.0,548028.0,398611.0,279622.0,423185.0,266187.0,514954.0,1467251.0,0.0,204581.0,460535.0,8147076.0,300459.0,308735.0,103618.0,327152.0,255803.0
2011 년,231991.0,1993306.0,529648.0,383890.0,270235.0,404951.0,257718.0,487642.0,1398625.0,0.0,196070.0,444360.0,7854617.0,288542.0,298452.0,101162.0,320275.0,247750.0
2012 년,224263.0,1947388.0,511366.0,369490.0,261426.0,387819.0,249805.0,463716.0,1335751.0,16144.0,188358.0,429852.0,7589751.0,277521.0,287972.0,99094.0,300874.0,238912.0
2013 년,217826.0,1911162.0,497818.0,357405.0,253579.0,372691.0,243058.0,443935.0,1281620.0,17435.0,181838.0,419022.0,7370691.0,268253.0,278974.0,97777.0,296151.0,232147.0
2014 년,209953.0,1865526.0,482788.0,344193.0,244343.0,355790.0,233933.0,424359.0,1228627.0,23212.0,174932.0,406191.0,7130507.0,257802.0,268797.0,96169.0,289628.0,224264.0
2015 년,202373.0,1822452.0,466690.0,331404.0,234548.0,339382.0,222210.0,405447.0,1173153.0,33303.0,168376.0,394105.0,6893407.0,248299.0,258506.0,95027.0,282600.0,215532.0
2016 년,195374.0,1791630.0,454038.0,320682.0,225420.0,325740.0,213255.0,390530.0,1122623.0,39060.0,162508.0,383843.0,6695799.0,239741.0,250080.0,94205.0,277887.0,209183.0
2017 년,188577.0,1767031.0,444781.0,312010.0,217369.0,314837.0,204839.0,376856.0,1081093.0,45969.0,157402.0,375038.0,6531675.0,232265.0,241592.0,94098.0,274606.0,203312.0
2018 년,182563.0,1755978.0,436234.0,304331.0,210686.0,304589.0,197553.0,367206.0,1043251.0,52481.0,153525.0,367447.0,6399567.0,225233.0,233771.0,94000.0,271824.0,198895.0
2019 년,175026.0,1720412.0,423485.0,294141.0,201884.0,291179.0,188948.0,354532.0,1000664.0,56938.0,148579.0,356790.0,6202006.0,215790.0,223851.0,91935.0,264953.0,192899.0
2020 년,169981.0,1708398.0,416356.0,287388.0,195826.0,282322.0,182923.0,347400.0,970916.0,60412.0,145644.0,349179.0,6083600.0,209178.0,216799.0,91630.0,260251.0,188997.0
2021 년,166826.0,1712879.0,413271.0,285346.0,192240.0,277727.0,179025.0,344711.0,947645.0,64155.0,144490.0,348002.0,6033002.0,205778.0,212207.0,92216.0,259441.0,187043.0
2022 년,163762.0,1699960.0,407191.0,280364.0,187913.0,272948.0,175131.0,340703.0,925501.0,67302.0,142794.0,346372.0,5952294.0,201596.0,206753.0,91691.0,257794.0,184519.0
2023 년,158969.0,1678141.0,398243.0,273108.0,183266.0,269521.0,170503.0,335736.0,900057.0,68660.0,140462.0,344236.0,5843938.0,196448.0,200759.0,90430.0,254523.0,180876.0

In [13]:
# 인덱스 이름 제거
region_df.rename_axis(None, inplace=True)

# 'index' 열의 이름을 '연도'로 변경
region_df.rename(columns={'index': '연도'}, inplace=True)

region_df

행정구역(시군구)별,강원특별자치도,경기도,경상남도,경상북도,광주광역시,대구광역시,대전광역시,부산광역시,서울특별시,세종특별자치시,울산광역시,인천광역시,전국,전라남도,전북특별자치도,제주특별자치도,충청남도,충청북도
2024.07 월,156825.0,1668342.0,393297.0,269892.0,180717.0,266929.0,168161.0,333411.0,889156.0,69295.0,138862.0,343115.0,5790242.0,193469.0,197056.0,89331.0,253159.0,179225.0
2008 년,249804.0,2089268.0,571890.0,422669.0,287703.0,448435.0,278105.0,555978.0,1555910.0,0.0,218053.0,486368.0,8510588.0,317399.0,322718.0,106045.0,334522.0,265721.0
2009 년,245303.0,2074456.0,562308.0,411780.0,285310.0,438090.0,273050.0,538515.0,1519140.0,0.0,212393.0,475349.0,8360727.0,310142.0,316556.0,105450.0,331484.0,261401.0
2010 년,239441.0,2048914.0,548028.0,398611.0,279622.0,423185.0,266187.0,514954.0,1467251.0,0.0,204581.0,460535.0,8147076.0,300459.0,308735.0,103618.0,327152.0,255803.0
2011 년,231991.0,1993306.0,529648.0,383890.0,270235.0,404951.0,257718.0,487642.0,1398625.0,0.0,196070.0,444360.0,7854617.0,288542.0,298452.0,101162.0,320275.0,247750.0
2012 년,224263.0,1947388.0,511366.0,369490.0,261426.0,387819.0,249805.0,463716.0,1335751.0,16144.0,188358.0,429852.0,7589751.0,277521.0,287972.0,99094.0,300874.0,238912.0
2013 년,217826.0,1911162.0,497818.0,357405.0,253579.0,372691.0,243058.0,443935.0,1281620.0,17435.0,181838.0,419022.0,7370691.0,268253.0,278974.0,97777.0,296151.0,232147.0
2014 년,209953.0,1865526.0,482788.0,344193.0,244343.0,355790.0,233933.0,424359.0,1228627.0,23212.0,174932.0,406191.0,7130507.0,257802.0,268797.0,96169.0,289628.0,224264.0
2015 년,202373.0,1822452.0,466690.0,331404.0,234548.0,339382.0,222210.0,405447.0,1173153.0,33303.0,168376.0,394105.0,6893407.0,248299.0,258506.0,95027.0,282600.0,215532.0
2016 년,195374.0,1791630.0,454038.0,320682.0,225420.0,325740.0,213255.0,390530.0,1122623.0,39060.0,162508.0,383843.0,6695799.0,239741.0,250080.0,94205.0,277887.0,209183.0
2017 년,188577.0,1767031.0,444781.0,312010.0,217369.0,314837.0,204839.0,376856.0,1081093.0,45969.0,157402.0,375038.0,6531675.0,232265.0,241592.0,94098.0,274606.0,203312.0
2018 년,182563.0,1755978.0,436234.0,304331.0,210686.0,304589.0,197553.0,367206.0,1043251.0,52481.0,153525.0,367447.0,6399567.0,225233.0,233771.0,94000.0,271824.0,198895.0
2019 년,175026.0,1720412.0,423485.0,294141.0,201884.0,291179.0,188948.0,354532.0,1000664.0,56938.0,148579.0,356790.0,6202006.0,215790.0,223851.0,91935.0,264953.0,192899.0
2020 년,169981.0,1708398.0,416356.0,287388.0,195826.0,282322.0,182923.0,347400.0,970916.0,60412.0,145644.0,349179.0,6083600.0,209178.0,216799.0,91630.0,260251.0,188997.0
2021 년,166826.0,1712879.0,413271.0,285346.0,192240.0,277727.0,179025.0,344711.0,947645.0,64155.0,144490.0,348002.0,6033002.0,205778.0,212207.0,92216.0,259441.0,187043.0
2022 년,163762.0,1699960.0,407191.0,280364.0,187913.0,272948.0,175131.0,340703.0,925501.0,67302.0,142794.0,346372.0,5952294.0,201596.0,206753.0,91691.0,257794.0,184519.0
2023 년,158969.0,1678141.0,398243.0,273108.0,183266.0,269521.0,170503.0,335736.0,900057.0,68660.0,140462.0,344236.0,5843938.0,196448.0,200759.0,90430.0,254523.0,180876.0

In [14]:
# 첫 행을 연도로 설정
region_df.columns.name = None
region_df = region_df.rename_axis('연도').reset_index()
region_df

,연도,강원특별자치도,경기도,경상남도,경상북도,광주광역시,대구광역시,대전광역시,부산광역시,서울특별시,세종특별자치시,울산광역시,인천광역시,전국,전라남도,전북특별자치도,제주특별자치도,충청남도,충청북도
0,2024.07 월,156825.0,1668342.0,393297.0,269892.0,180717.0,266929.0,168161.0,333411.0,889156.0,69295.0,138862.0,343115.0,5790242.0,193469.0,197056.0,89331.0,253159.0,179225.0
1,2008 년,249804.0,2089268.0,571890.0,422669.0,287703.0,448435.0,278105.0,555978.0,1555910.0,0.0,218053.0,486368.0,8510588.0,317399.0,322718.0,106045.0,334522.0,265721.0
2,2009 년,245303.0,2074456.0,562308.0,411780.0,285310.0,438090.0,273050.0,538515.0,1519140.0,0.0,212393.0,475349.0,8360727.0,310142.0,316556.0,105450.0,331484.0,261401.0
3,2010 년,239441.0,2048914.0,548028.0,398611.0,279622.0,423185.0,266187.0,514954.0,1467251.0,0.0,204581.0,460535.0,8147076.0,300459.0,308735.0,103618.0,327152.0,255803.0
4,2011 년,231991.0,1993306.0,529648.0,383890.0,270235.0,404951.0,257718.0,487642.0,1398625.0,0.0,196070.0,444360.0,7854617.0,288542.0,298452.0,101162.0,320275.0,247750.0
5,2012 년,224263.0,1947388.0,511366.0,369490.0,261426.0,387819.0,249805.0,463716.0,1335751.0,16144.0,188358.0,429852.0,7589751.0,277521.0,287972.0,99094.0,300874.0,238912.0
6,2013 년,217826.0,1911162.0,497818.0,357405.0,253579.0,372691.0,243058.0,443935.0,1281620.0,17435.0,181838.0,419022.0,7370691.0,268253.0,278974.0,97777.0,296151.0,232147.0
7,2014 년,209953.0,1865526.0,482788.0,344193.0,244343.0,355790.0,233933.0,424359.0,1228627.0,23212.0,174932.0,406191.0,7130507.0,257802.0,268797.0,96169.0,289628.0,224264.0
8,2015 년,202373.0,1822452.0,466690.0,331404.0,234548.0,339382.0,222210.0,405447.0,1173153.0,33303.0,168376.0,394105.0,6893407.0,248299.0,258506.0,95027.0,282600.0,215532.0
9,2016 년,195374.0,1791630.0,454038.0,320682.0,225420.0,325740.0,213255.0,390530.0,1122623.0,39060.0,162508.0,383843.0,6695799.0,239741.0,250080.0,94205.0,277887.0,209183.0
10,2017 년,188577.0,1767031.0,444781.0,312010.0,217369.0,314837.0,204839.0,376856.0,1081093.0,45969.0,157402.0,375038.0,6531675.0,232265.0,241592.0,94098.0,274606.0,203312.0
11,2018 년,182563.0,1755978.0,436234.0,304331.0,210686.0,304589.0,197553.0,367206.0,1043251.0,52481.0,153525.0,367447.0,6399567.0,225233.0,233771.0,94000.0,271824.0,198895.0
12,2019 년,175026.0,1720412.0,423485.0,294141.0,201884.0,291179.0,188948.0,354532.0,1000664.0,56938.0,148579.0,356790.0,6202006.0,215790.0,223851.0,91935.0,264953.0,192899.0
13,2020 년,169981.0,1708398.0,416356.0,287388.0,195826.0,282322.0,182923.0,347400.0,970916.0,60412.0,145644.0,349179.0,6083600.0,209178.0,216799.0,91630.0,260251.0,188997.0
14,2021 년,166826.0,1712879.0,413271.0,285346.0,192240.0,277727.0,179025.0,344711.0,947645.0,64155.0,144490.0,348002.0,6033002.0,205778.0,212207.0,92216.0,259441.0,187043.0
15,2022 년,163762.0,1699960.0,407191.0,280364.0,187913.0,272948.0,175131.0,340703.0,925501.0,67302.0,142794.0,346372.0,5952294.0,201596.0,206753.0,91691.0,257794.0,184519.0
16,2023 년,158969.0,1678141.0,398243.0,273108.0,183266.0,269521.0,170503.0,335736.0,900057.0,68660.0,140462.0,344236.0,5843938.0,196448.0,200759.0,90430.0,254523.0,180876.0

In [15]:
region_df.columns
region_df.index

RangeIndex(start=0, stop=17, step=1)

In [16]:
# '연도' 컬럼을 인덱스로 설정
region_df.set_index('연도', inplace=True)
region_df

,강원특별자치도,경기도,경상남도,경상북도,광주광역시,대구광역시,대전광역시,부산광역시,서울특별시,세종특별자치시,울산광역시,인천광역시,전국,전라남도,전북특별자치도,제주특별자치도,충청남도,충청북도
연도,,,,,,,,,,,,,,,,,,
2024.07 월,156825.0,1668342.0,393297.0,269892.0,180717.0,266929.0,168161.0,333411.0,889156.0,69295.0,138862.0,343115.0,5790242.0,193469.0,197056.0,89331.0,253159.0,179225.0
2008 년,249804.0,2089268.0,571890.0,422669.0,287703.0,448435.0,278105.0,555978.0,1555910.0,0.0,218053.0,486368.0,8510588.0,317399.0,322718.0,106045.0,334522.0,265721.0
2009 년,245303.0,2074456.0,562308.0,411780.0,285310.0,438090.0,273050.0,538515.0,1519140.0,0.0,212393.0,475349.0,8360727.0,310142.0,316556.0,105450.0,331484.0,261401.0
2010 년,239441.0,2048914.0,548028.0,398611.0,279622.0,423185.0,266187.0,514954.0,1467251.0,0.0,204581.0,460535.0,8147076.0,300459.0,308735.0,103618.0,327152.0,255803.0
2011 년,231991.0,1993306.0,529648.0,383890.0,270235.0,404951.0,257718.0,487642.0,1398625.0,0.0,196070.0,444360.0,7854617.0,288542.0,298452.0,101162.0,320275.0,247750.0
2012 년,224263.0,1947388.0,511366.0,369490.0,261426.0,387819.0,249805.0,463716.0,1335751.0,16144.0,188358.0,429852.0,7589751.0,277521.0,287972.0,99094.0,300874.0,238912.0
2013 년,217826.0,1911162.0,497818.0,357405.0,253579.0,372691.0,243058.0,443935.0,1281620.0,17435.0,181838.0,419022.0,7370691.0,268253.0,278974.0,97777.0,296151.0,232147.0
2014 년,209953.0,1865526.0,482788.0,344193.0,244343.0,355790.0,233933.0,424359.0,1228627.0,23212.0,174932.0,406191.0,7130507.0,257802.0,268797.0,96169.0,289628.0,224264.0
2015 년,202373.0,1822452.0,466690.0,331404.0,234548.0,339382.0,222210.0,405447.0,1173153.0,33303.0,168376.0,394105.0,6893407.0,248299.0,258506.0,95027.0,282600.0,215532.0
2016 년,195374.0,1791630.0,454038.0,320682.0,225420.0,325740.0,213255.0,390530.0,1122623.0,39060.0,162508.0,383843.0,6695799.0,239741.0,250080.0,94205.0,277887.0,209183.0
2017 년,188577.0,1767031.0,444781.0,312010.0,217369.0,314837.0,204839.0,376856.0,1081093.0,45969.0,157402.0,375038.0,6531675.0,232265.0,241592.0,94098.0,274606.0,203312.0
2018 년,182563.0,1755978.0,436234.0,304331.0,210686.0,304589.0,197553.0,367206.0,1043251.0,52481.0,153525.0,367447.0,6399567.0,225233.0,233771.0,94000.0,271824.0,198895.0
2019 년,175026.0,1720412.0,423485.0,294141.0,201884.0,291179.0,188948.0,354532.0,1000664.0,56938.0,148579.0,356790.0,6202006.0,215790.0,223851.0,91935.0,264953.0,192899.0
2020 년,169981.0,1708398.0,416356.0,287388.0,195826.0,282322.0,182923.0,347400.0,970916.0,60412.0,145644.0,349179.0,6083600.0,209178.0,216799.0,91630.0,260251.0,188997.0
2021 년,166826.0,1712879.0,413271.0,285346.0,192240.0,277727.0,179025.0,344711.0,947645.0,64155.0,144490.0,348002.0,6033002.0,205778.0,212207.0,92216.0,259441.0,187043.0
2022 년,163762.0,1699960.0,407191.0,280364.0,187913.0,272948.0,175131.0,340703.0,925501.0,67302.0,142794.0,346372.0,5952294.0,201596.0,206753.0,91691.0,257794.0,184519.0
2023 년,158969.0,1678141.0,398243.0,273108.0,183266.0,269521.0,170503.0,335736.0,900057.0,68660.0,140462.0,344236.0,5843938.0,196448.0,200759.0,90430.0,254523.0,180876.0

In [17]:
# 아동1 지역 리스트
child1_regions = ['강원특별자치도','경상남도','경상북도','전라남도','전북특별자치도','충청남도','충청북도']

# 아동1 컬럼 합치기
region_df['아동1'] = region_df[child1_regions].sum(axis=1)

# 아동2 지역 리스트 (아동1, '전체국민' 제외)
child2_regions = [region for region in region_df.columns if region not in child1_regions + ['전국']]

# 아동2 컬럼 합치기 전에 숫자형으로 변환
region_df[child2_regions] = region_df[child2_regions].apply(pd.to_numeric, errors='coerce')
region_df['아동2'] = region_df[child2_regions].sum(axis=1)

# 필요한 컬럼만 저장
#region_df = region_df[['연도','전국', '아동1', '아동2']]
region_df = region_df[['전국', '아동1', '아동2']]

region_df

                  전국        아동1        아동2
연도
2024.07 월  5790242.0  1642923.0  5790242.0
2008 년     8510588.0  2484723.0  8510588.0
2009 년     8360727.0  2438974.0  8360727.0
2010 년     8147076.0  2378229.0  8147076.0
2011 년     7854617.0  2300548.0  7854617.0
2012 년     7589751.0  2210398.0  7589751.0
2013 년     7370691.0  2148574.0  7370691.0
2014 년     7130507.0  2077425.0  7130507.0
2015 년     6893407.0  2005404.0  6893407.0
2016 년     6695799.0  1946985.0  6695799.0
2017 년     6531675.0  1897143.0  6531675.0
2018 년     6399567.0  1852851.0  6399567.0
2019 년     6202006.0  1790145.0  6202006.0
2020 년     6083600.0  1748950.0  6083600.0
2021 년     6033002.0  1729912.0  6033002.0
2022 년     5952294.0  1701979.0  5952294.0
2023 년     5843938.0  1662926.0  5843938.0

In [18]:
region_df

                  전국        아동1        아동2
연도
2024.07 월  5790242.0  1642923.0  5790242.0
2008 년     8510588.0  2484723.0  8510588.0
2009 년     8360727.0  2438974.0  8360727.0
2010 년     8147076.0  2378229.0  8147076.0
2011 년     7854617.0  2300548.0  7854617.0
2012 년     7589751.0  2210398.0  7589751.0
2013 년     7370691.0  2148574.0  7370691.0
2014 년     7130507.0  2077425.0  7130507.0
2015 년     6893407.0  2005404.0  6893407.0
2016 년     6695799.0  1946985.0  6695799.0
2017 년     6531675.0  1897143.0  6531675.0
2018 년     6399567.0  1852851.0  6399567.0
2019 년     6202006.0  1790145.0  6202006.0
2020 년     6083600.0  1748950.0  6083600.0
2021 년     6033002.0  1729912.0  6033002.0
2022 년     5952294.0  1701979.0  5952294.0
2023 년     5843938.0  1662926.0  5843938.0

# 4. index 연도 int형으로 바꿔주기

In [19]:
int_df = region_df.copy()
int_df

                  전국        아동1        아동2
연도
2024.07 월  5790242.0  1642923.0  5790242.0
2008 년     8510588.0  2484723.0  8510588.0
2009 년     8360727.0  2438974.0  8360727.0
2010 년     8147076.0  2378229.0  8147076.0
2011 년     7854617.0  2300548.0  7854617.0
2012 년     7589751.0  2210398.0  7589751.0
2013 년     7370691.0  2148574.0  7370691.0
2014 년     7130507.0  2077425.0  7130507.0
2015 년     6893407.0  2005404.0  6893407.0
2016 년     6695799.0  1946985.0  6695799.0
2017 년     6531675.0  1897143.0  6531675.0
2018 년     6399567.0  1852851.0  6399567.0
2019 년     6202006.0  1790145.0  6202006.0
2020 년     6083600.0  1748950.0  6083600.0
2021 년     6033002.0  1729912.0  6033002.0
2022 년     5952294.0  1701979.0  5952294.0
2023 년     5843938.0  1662926.0  5843938.0

In [20]:
# 인덱스를 컬럼으로 변환
int_df = int_df.reset_index()

# '연도' 컬럼에서 숫자 부분만 추출하고 정수형으로 변환
int_df['연도'] = int_df['연도'].str.extract(r'(\d{4})').astype(int)

# 변경된 '연도' 컬럼을 다시 인덱스로 설정
int_df = int_df.set_index('연도')

In [21]:
int_df

             전국        아동1        아동2
연도
2024  5790242.0  1642923.0  5790242.0
2008  8510588.0  2484723.0  8510588.0
2009  8360727.0  2438974.0  8360727.0
2010  8147076.0  2378229.0  8147076.0
2011  7854617.0  2300548.0  7854617.0
2012  7589751.0  2210398.0  7589751.0
2013  7370691.0  2148574.0  7370691.0
2014  7130507.0  2077425.0  7130507.0
2015  6893407.0  2005404.0  6893407.0
2016  6695799.0  1946985.0  6695799.0
2017  6531675.0  1897143.0  6531675.0
2018  6399567.0  1852851.0  6399567.0
2019  6202006.0  1790145.0  6202006.0
2020  6083600.0  1748950.0  6083600.0
2021  6033002.0  1729912.0  6033002.0
2022  5952294.0  1701979.0  5952294.0
2023  5843938.0  1662926.0  5843938.0

In [25]:
# CSV 파일로 저장 (UTF-8 인코딩)
csv_filename = '인구전처리_1차.csv'
int_df.to_csv(csv_filename, encoding='utf-8')

# 파일 다운로드
files.download(csv_filename)

In [27]:
# CSV 파일로 저장 (cp949 인코딩)
csv_filename = '인구전처리_1차.csv'
int_df.to_csv(csv_filename, encoding='cp949')

# 파일 다운로드
files.download(csv_filename)